### ISSUE TITLE
Rework yaml config for easier multiplayer setup

### ISSUE THREAD

**Issue by lizadaly** [lizadaly/windrift#49]
The current config does not allow players to start in different chapters.

Instead of a separate `config.multiplayer` block (which is easy to confuse with the `mulitplayer` store object), define a `players` block and define a multiplayer game as one with multiple defined players.

In a single person story, there should be only one `player` entry, and a `start` key pointing to a chapters entry will define which key is marked as `visible` on setup.

Example single player:

```
chapters:
  - chapter:
     filename: "chapter1"
players:
  - start: "chapter1"
```

Example multiplayer: 

```
chapters:
  - chapter:
     filename: "prologue"
  - chapter:
     filename: "chapter1"
players:
  - name: "sidekick"
    start: "chapter1"
  - name: "protagonist" 
    start: "prologue"

```
